// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe8KXYzGlKHMDLeTyLhvH-uPtbeZe12RY',
    appId: '1:837737308428:web:9061bdbf1743b62fb1e929',
    messagingSenderId: '837737308428',
    projectId: 'sigflod-m-d35b4',
    authDomain: 'sigflod-m-d35b4.firebaseapp.com',
    storageBucket: 'sigflod-m-d35b4.firebasestorage.app',
    measurementId: 'G-WCP51PYFSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-qczmOve5OfG7rQSeaE2TgKQyILT1r8',
    appId: '1:837737308428:android:1f51a0f7cb2d2fdeb1e929',
    messagingSenderId: '837737308428',
    projectId: 'sigflod-m-d35b4',
    storageBucket: 'sigflod-m-d35b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYci6Ge6wcQWgMtnnCdOawlK3ghZ6glZU',
    appId: '1:837737308428:ios:336a7717c6b62e6db1e929',
    messagingSenderId: '837737308428',
    projectId: 'sigflod-m-d35b4',
    storageBucket: 'sigflod-m-d35b4.firebasestorage.app',
    iosClientId:
        '837737308428-1737i7oavhip9qak83i90ebcn6k33j0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigflod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYci6Ge6wcQWgMtnnCdOawlK3ghZ6glZU',
    appId: '1:837737308428:ios:336a7717c6b62e6db1e929',
    messagingSenderId: '837737308428',
    projectId: 'sigflod-m-d35b4',
    storageBucket: 'sigflod-m-d35b4.firebasestorage.app',
    iosClientId:
        '837737308428-1737i7oavhip9qak83i90ebcn6k33j0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigflod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe8KXYzGlKHMDLeTyLhvH-uPtbeZe12RY',
    appId: '1:837737308428:web:93c3f239e3c9ab07b1e929',
    messagingSenderId: '837737308428',
    projectId: 'sigflod-m-d35b4',
    authDomain: 'sigflod-m-d35b4.firebaseapp.com',
    storageBucket: 'sigflod-m-d35b4.firebasestorage.app',
    measurementId: 'G-L6CWZE1S51',
  );
}
